spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres/
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9092

  mail:
    host: localhost
    port: 1026
    username: test
    password: test
    from: noreply@trailracer.com
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
    use-mock: false

frontend:
  url: http://localhost:4200

application:
  security:
    jwt:
      secret-key: ZjMzYzM4NzYzMTg0OWE4ZTY5M2ZlYjZhMDIyMjA4ZGQzYTNlZmQ4ZmU0MzU3ZThhNTc1Yzg1NTZiYzEyY2VlNzM5ZGM2MjdkMGY5NWMyY2Y5NmRiMDg3ZGFkOTM3NWEwODA5ODJjZWQ3NGI0MDdiMzZmYzlhOGU0NTEyODFmYzg=
