services:
  postgres:
    image: 'postgres:18.1-alpine3.22'
    hostname: postgres
    restart: always
    container_name: trail_racer_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  maildev:
    image: maildev/maildev
    ports:
      - '1081:1080'
      - '1026:1025'
    volumes:
      - ./maildev-data:/home/maildev/data
    command: bin/maildev --mail-directory /home/maildev/data

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CLUSTER_ID: NkYxMDE1MzAxNDc5NDc1ZTAzNzI1NDhj

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://localhost:9094,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    restart: always

  command-service:
    image: image/command-service:latest
    build:
      context: ../command-service
      dockerfile: none
    container_name: command-service
    depends_on:
      - postgres
      - kafka
      - maildev
    environment:
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - "8080:8080"
    restart: unless-stopped

  query-service:
    image: image/query-service:latest
    build:
      context: ../query-service
      dockerfile: none
    container_name: query-service
    depends_on:
      - command-service
    environment:
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - "8081:8081"
    restart: unless-stopped
